version: 2
jobs:
    build:
      working_directory: ~/project
      docker:
        - image: circleci/php:7.3-node
      steps:
        - checkout
        - run:
            name: "Build Api on lambda"
            command: |
             cd ~/project
             sudo npm install -g serverless
             composer install
             serverless deploy